apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 1h
  path: ./04-gitops # Aponta para a pasta onde está o flagger.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system